services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CREATE_TASK_USER_RATE_LIMIT=${CREATE_TASK_USER_RATE_LIMIT}
      - CREATE_TASK_USER_RATE_PERIOD=${CREATE_TASK_USER_RATE_PERIOD}
      - CREATE_TASK_GLOBAL_RATE_LIMIT=${CREATE_TASK_GLOBAL_RATE_LIMIT}
      - CREATE_TASK_GLOBAL_RATE_PERIOD=${CREATE_TASK_GLOBAL_RATE_PERIOD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
  